url: https://nilsonlinux.github.io
title: Nilsonlinux
description: Blog em desenvolvimento by; Nilsonlinux Web Developer.
keywords: nilsonlinux, jekyll, jekyll-theme-docs
image: /assets/img/social.svg
email: nilsonlinux@gmail.com
timezone: America/Sao_Paulo
branch: master
lang: pt_BR
contact_url: https://script.google.com/macros/s/AKfycbzO2JBqXFqIX8qQc37BkZvL4Ijsz2NdwhQTESyc/exec
twitter_username: nilsonlinux
facebook_username: nilsonlinux
google-plus_username: +Nilsonlinux
telegram_username: Nilsonlinux
github_username: nilsonlinux
stackoverflow_username: 10241849/nilsonlinux
last-fm_username: nilsonlinux
linkedin_username: nilsonlinux-2236a814b
youtube_username: UCm9Bng8syg_XATxebmhoIgA?view_as=subscriber
instagram_username: nilsonlinux
author:
  name: Nilsonlinux
  email: nilsonlinux@gmail.com
twitter:
  site: null
  creator: nilsonlinux
google:
  site-verification: 7YAsvH47ykUFB4n7rYiqT6A9mi0WF5y_DjzRtUco4IY
  analytics: UA-122784671-1 # <--google Nilsonlinux-id-Substitua-->
  cse-cx: 005886127669980887444:4bc5lc9r79e
  api-key: AIzaSyA3zsF5TE9uKWxRbkQxFLWLvw7-i3ER214
disqus_shortname: nilsonlinux
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      permalink: /:categories/:title

